# Generated by Django 4.1.7 on 2023-03-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.TextField()),
                ('user_id', models.CharField(max_length=60)),
                ('image', models.TextField()),
                ('content', models.TextField()),
                ('like_count', models.IntegerField()),
            ],
        ),
    ]
