# Generated by Django 4.1.7 on 2023-03-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='user_id',
            field=models.TextField(),
        ),
    ]
