# Generated by Django 4.1.7 on 2023-04-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_like_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='like_count',
        ),
    ]
